import React from 'react';
import Head from 'next/head';
import Card from '../components/Card';
import {
  ChartPieIcon,
  LibraryIcon,
  TrendingUpIcon,
} from '@heroicons/react/outline';

export default function capital() {
  return (
    <div className='bg-gray-50'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='max-w-7xl mx-auto px-2 sm:px-6 lg:px-8 font-roboto py-10 '>
        <div className='flex items-center justify-between'>
          <Card
            title='Supplied capital'
            amount='0'
            unit='CKB'
            icon={<LibraryIcon className='block h-8 w-8 text-white' />}
          />
          <Card
            title='Acive capital pools'
            amount='0'
            icon={<ChartPieIcon className='block h-8 w-8 text-white' />}
          />
          <Card
            title='Total APY'
            amount='0'
            icon={<TrendingUpIcon className='block h-8 w-8 text-white' />}
          />
        </div>
      </div>
    </div>
  );
}
