import Head from 'next/head';
import {
  ShieldCheckIcon,
  TagIcon,
  CollectionIcon,
  CashIcon,
  StatusOnlineIcon,
} from '@heroicons/react/outline';

import Stat from '../components/Stat';
import Card from '../components/Card';

export default function Cover() {
  return (
    <div className='bg-gray-50 font-roboto'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='bg-gray-800'>
        <div className='max-w-7xl mx-auto px-2 sm:px-6 lg:px-8'>
          <div className='flex flex-wrap items-center justify-between py-10 border border-l-0 border-r-0 border-b-0 border-gray-700'>
            <Stat
              title='Total cover value'
              amount='0'
              icon={<CashIcon className='block h-8 w-8 text-white' />}
            />
            <Stat
              title='Total covers'
              amount='0'
              icon={<CollectionIcon className='block h-8 w-8 text-white' />}
            />
            <Stat
              title='Total active covers'
              amount='0'
              icon={<StatusOnlineIcon className='block h-8 w-8 text-white' />}
            />
          </div>
        </div>
      </div>
      <div className='max-w-7xl mx-auto px-2 sm:px-6 lg:px-8'>
        <div className='py-10'>
          <div className='flex flex-wrap items-center justify-between'>
            <Card asset='ETH' type='Collateral Protection' premium='10' />
          </div>
        </div>
      </div>
    </div>
  );
}
