import Head from 'next/head';
import {
  ShieldCheckIcon,
  TagIcon,
  CollectionIcon,
} from '@heroicons/react/outline';
import { useEffect, useState } from 'react';

import Card from '../components/Card';

import { getClientContract } from '../web3/insuranceprovider';
import {
  getContractStatus,
  getPayoutValue,
  getPremium,
} from '../web3/insurancecontract';

export default function Home() {
  const [totalCover, setTotalCover] = useState(0);
  const [premium, setPremium] = useState(0);

  useEffect(() => {
    fetchClientDetails();
    window.ethereum.on('accountsChanged', fetchClientDetails);
  }, []);

  const fetchClientDetails = async function (_) {
    const clientAddr = window.ethereum.selectedAddress;
    if (clientAddr) {
      const clientContract = await getClientContract(clientAddr);
      if (clientContract != '0x'.padEnd(40, '0')) {
        const payoutValue = await getPayoutValue(clientContract);
        const premium = await getPremium(clientContract);
        setTotalCover(payoutValue / 10 ** 8);
        setPremium(premium / 10 ** 8);
      }
    }
  };

  return (
    <div className='bg-gray-50'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='max-w-7xl mx-auto px-2 sm:px-6 lg:px-8 font-roboto py-10 '>
        <div className='flex items-center justify-between'>
          <Card
            title='Total cover'
            amount={totalCover}
            unit='CKB'
            icon={<ShieldCheckIcon className='block h-8 w-8 text-white' />}
          />
          <Card
            title='No of active covers'
            amount='0'
            icon={<CollectionIcon className='block h-8 w-8 text-white' />}
          />
          <Card
            title='Insurance fee'
            amount={premium}
            unit='CKB'
            pm
            icon={<TagIcon className='block h-8 w-8 text-white' />}
          />
        </div>
      </div>
    </div>
  );
}
